name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: guerric-p/cf-cli-action@master
      with:
        cf_api: https://api.cf.ap21.hana.ondemand.com
        cf_username: ramyaravindra999@gmail.com
        cf_password: Azuredevops@123
        cf_org: 6fece677trial
        cf_space: prod
        command: push MY-APP –p https://github.com/san39/rock-paper-scissors/gs-spring-boot-0.1.0.jar
